### ISSUE TITLE
Error while using poisson model

### ISSUE THREAD

**Issue by ladm2110** [mingstat/ZIM#2]
It appears to be something wrong with an if defined inside "zim" method.
Next appears the code which gives the error...

> count = c(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 650.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 300.0, 0.0, 0.0, 0.0, 0.0, 2100.0, 1600.0, 400.0, 750.0, 0.0, 0.0, 0.0, 1400.0, 620.0, 0.0, 600.0, 600.0, 0.0, 0.0, 2300.0, 0.0, 1950.0, 0.0, 750.0, 0.0, 0.0, 500.0, 300.0, 0.0, 0.0, 0.0, 0.0, 0.0, 350.0, 0.0, 350.0, 0.0, 2600.0, 0.0, 0.0, 2000.0, 0.0, 750.0, 5500.0, 900.0, 0.0, 0.0, 0.0, 350.0, 2200.0, 200.0, 0.0, 0.0, 0.0, 480.0, 0.0, 0.0, 0.0, 350.0, 0.0, 0.0, 340.0, 200.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1700.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 440.0, 300.0, 0.0, 0.0, 140.0, 200.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1000.0, 350.0, 190.0, 0.0, 400.0, 0.0, 0.0, 0.0, 900.0, 750.0, 0.0, 850.0, 0.0, 0.0, 0.0, 1000.0, 0.0, 800.0, 300.0, 0.0, 0.0, 590.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1680.0, 1000.0, 350.0, 0.0, 0.0, 0.0, 0.0, 475.9, 500.0, 2500.0, 200.0, 200.0, 0.0, 0.0, 460.0, 0.0, 2700.0, 0.0, 1800.0, 0.0, 0.0, 1600.0, 450.0, 0.0, 0.0, 500.0, 0.0, 0.0, 1100.0, 0.0, 0.0, 250.0, 0.0, 0.0, 0.0, 600.0, 2800.0, 0.0, 1160.0, 0.0, 0.0, 0.0, 3000.0, 750.0, 0.0, 350.0, 1900.0, 0.0, 0.0, 0.0, 0.0, 2200.0, 0.0, 0.0, 0.0, 0.0, 600.0, 0.0, 0.0, 0.0, 900.0, 0.0, 0.0, 600.0, 0.0, 0.0, 500.0, 0.0, 0.0, 0.0, 0.0, 0.0, 880.0, 0.0, 0.0, 0.0, 0.0, 800.0, 0.0, 0.0, 3290.0, 0.0, 0.0, 0.0, 1150.0, 0.0, 3000.0, 0.0, 300.0, 0.0, 0.0, 2100.0, 0.0, 600.0, 0.0, 1300.0, 0.0, 0.0, 0.0, 90.0, 150.0, 0.0, 1000.0, 0.0, 0.0, 1400.0, 0.0, 0.0, 0.0, 2800.0, 0.0, 0.0, 0.0, 1100.0, 0.0, 1150.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 600.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2900.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2600.0, 0.0, 0.0, 0.0, 0.0, 1050.0, 1600.0, 0.0, 0.0, 0.0, 0.0, 0.0, 600.0, 0.0, 0.0, 1300.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1650.0, 0.0, 0.0, 0.0, 850.0, 0.0, 1350.0, 0.0, 0.0, 0.0, 0.0, 900.0, 0.0, 0.0, 0.0, 1150.0, 0.0, 0.0, 0.0, 0.0, 900.0, 490.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1200.0, 0.0, 0.0, 0.0, 0.0, 1700.0, 2550.0, 0.0)
> count = floor(count)
> count.lag1 <- bshift(count > 0)
> trend <- 1:length(count) / 1000
> m1 = zim(count ~ count.lag1 + trend | trend)
Error in if (abs(loglik.new - loglik.old)/(abs(loglik.new) + control$epsilon) >  : 
  valor ausente donde TRUE/FALSE es necesario
Translation: (missing value where TRUE/FALSE is needed)

If I use the negative binomial distribution all goes well.

**Comment by mingstat** [comment]
The Poisson distribution assumes equal mean and variance. For your data, the variance is substantially larger than the mean. Thus, the negative binomial distribution might be more appropriate as it has an extra dispersion parameter.
